### ISSUE TITLE
Error in Task Description Array Basics / Create Empty Array

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/Python-Libraries-NumPy#46]
The output of a = np.zeros((3, 4)) is showing a 4x3 2D array instead of a 3x4 2D array.

**Comment by sofiiako** [comment]
Hi! np.zeros creates an array the way it is supposed to :) 
Please check out the docs for more information https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
