### ISSUE TITLE
 Array Indexing and Slicing / Indexing Basics

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/Python-Libraries-NumPy#53]
1.The solution proposed by JB for the variable a = x[4, 3] assumes only positive indices and does not allow negative indices a = x[4, -1] , although the latter is more convenient in such a case. Both solutions are equal and admissible. Correct pls if possible.
2. The second task requires extracting "every second element in every second row". According to JB's solution, the string x[0] is the "second string", although formally 0 != 2. In my opinion, it is better to specify the task by replacing the words "second" with "even" . Thanks.

**Comment by sofiiako** [comment]
Hi! Thank you for your feedback!
1) The solution x[4, -1] is accepted as correct by the test. I agree though, that it is a more obvious way to solve the task, so I changed the proposed solution. 
2) I believe the phrase "every second item" has a very specific meaning, but I added a note clarifying the task. Thank you again for pointing this out!
