### ISSUE TITLE
somedata.csv is bugged Array Basics / Reading and Writing Files

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/Python-Libraries-NumPy#71]
Even tho I have same code as in solution it even says "identical" the output is (0, ) instead (100, 4) and after looking at the file somedata.csv it looks like it's bugged so I can't finish the task
(0,)
float64
C:\Users\PCG\PycharmProjects\Python Libraries - NumPy\NumPy\Array Basics\Reading and Writing Files\task.py:4: UserWarning: genfromtxt: Empty input file: "somedata.csv"
  arr = np.genfromtxt(data, delimiter=',', skip_header=3)

**Comment by DaniilBogdanovJB** [comment]
Duplicates https://github.com/jetbrains-academy/Python-Libraries-NumPy/issues/71
